channels:
  - conda-forge
dependencies:
  - blas
  - numpy
  - pandas
  - pymc3
  - matplotlib
  - pandas-profiling
  - pip
  - pip:
    - arviz
    - streamlit
    - mpld3
    - streamlit-pandas-profiling